package com.rivancic.java.genericscollections;

import java.util.Arrays;
import java.util.List;
import org.junit.Test;
import static org.junit.Assert.assertEquals;

public class ArraysAsListTest {

  /**
   * One can not add additional elements to the list generated by the Arrays.asList factory method.
   * As this list is backed up by the array.
   */
  @Test(expected = UnsupportedOperationException.class)
  public void arraysAsListAdditionTest() {
    List<String> array = Arrays.asList("a", "b", "c", "d");
    array.add("l");
    assertEquals(5, array.size());
  }
}
